### ISSUE TITLE
Messaging with marblejs

### ISSUE THREAD

**Issue by damianesteban** [marblejs/marble#107]
I’m a big fan of marblejs - I’ve been following it closely since the early releases and I love the simplicity of its design. 

Has anyone proposed that marblejs expand to include messaging capabilities (i.e. NATS, grpc, SQS, etc.). The fact that it is lightweight and simple makes it a great candidate for microservices that rely on messaging. I think NATS in particular could be a good fit.

**Comment by JozefFlakus** [comment]
@damianesteban thanks for kind words! 💪

Not yet. Doors are open. 😋I agree it would be a good fit especially from version 2.0, which will be released soon. Would you like to discuss this topic more deeply? I'm really curious about your idea.

**Comment by damianesteban** [comment]
Sure I would be happy to. I just need to wrap up a few things this week and then I'll reach out to you.

**Comment by damianesteban** [comment]
Congratulations on the 2.0 release! When/how would you like to talk about this idea in more detail?

**Comment by JozefFlakus** [comment]
Tanks @damianesteban! I hope you'll like it! 💪
Just try to describe here in more detail your idea for the concept - I'm very responsive :). It will be the most transparent way I think.

**Comment by JozefFlakus** [comment]
@damianesteban I would like to start working on the `@marblejs/messaging` package soon.

Right now the raw idea is to make a reusable abstraction over it, with the ability for defining the transport layer, eg. **RabbitMQ**, **NATS**, etc. For the MVP purpose I would like to start with **RabbitMQ** and then, later on, extend the available transport layers to different ones. From the connection side, I see it as an injectable dependency that can be registered when the server is bootstrapped, eg. like we currently have in case of WebSocket package. That's why I mentioned that the 2.x release will perfectly fit it. Do you have any thoughts about it?

**Comment by damianesteban** [comment]
Hello. Yes I do have some thoughts. I'll write something up this evening.

**Comment by JozefFlakus** [comment]
Closing due to incoming release of version 3.0 with official support for microservices/messaging.
