### ISSUE TITLE
Type error thrown in logger middleware

### ISSUE THREAD

**Issue by karikalanarun** [marblejs/marble#157]
I have used fp-ts in my project and that has a version of ^2.0.1 and I have used [@marblejs/middleware-logger ](https://github.com/marblejs/marble/tree/master/packages/middleware-logger) to log my requests. when I request my server that exited with the error below.

> TypeError: Option_1.fromNullable(...).map is not a function
 in the file, /node_modules/@marblejs/middleware-logger/dist/logger.util.js:8:10)

Then, I inspected your code, that package also using fp-ts in the old style (.map, .getOrElse). 
I don't know, how to debug this.

And, I hesitated to use other middlewares. Because of other package also use that lib in the same manner.

**Comment by karikalanarun** [comment]
I have found what is the issue. you mentioned the fp-ts version in the core package. but, you didn't mention that version in that middleware package mentioned. so, the node takes the fp-ts version from mine. that is the problem. I guess. I will fix and raise a pull request soon

**Comment by JozefFlakus** [comment]
@karikalanarun I'm not sure if PR #158 will fix your issue. Maybe it will be a temporary solution but from a longer perspective, it will be not enough. Marble.js is based on `fp-ts v1.x` and is exposed mostly in the Context API. If you will try to use version 2 then I'm afraid that you will face conflicts with package version resolution when trying to play with Context API.

In general, Marble.js will support `fp-ts v2` in the next major release but so far we cannot introduce it because of the breaking changes that it will introduce.

**Comment by karikalanarun** [comment]
Okay @JozefFlakus , But is there any work around can you provide for this time?.

**Comment by JozefFlakus** [comment]
Sadly no. Marble.js v2 doesn't support `fp-ts v2`. You have to be patient and wait for official support in the upcoming next major release. For now, I would recommend using the previous version.

**Comment by JozefFlakus** [comment]
Closing due to incoming release of version 3.0 which comes with official support for `fp-ts v2`
