### ISSUE TITLE
3.0 Release date

### ISSUE THREAD

**Issue by enricosecondulfo** [marblejs/marble#207]
Hello guys,
thank you so much for the hard work creating a gorgeous framework like marblejs. 
I would like to know if exists a potentially release date and if the test package will come with the new release. 
Also will the examples repository be updated?

Thank you again

**Comment by JozefFlakus** [comment]
Hi @enricosecondulfo, thanks for your kind words!

1. As you can see the version 3.0 is under heavy development and testing. It is nearly done but requires few improvements and missing features that are still in my head. About one week ago I encountered a huge issue with improved `@marblejs/core` in HTTP routing mechanism which was still available under nightly build, so I had to rethink this idea again #206. But I've managed to solve it yesterday so everything went to the correct tracks. I'll explain it in the aftermentioned issue.

2. Sadly but it wasn't planned for the next major release. I suppose that it will be delivered in a minor release since we have a working module that is used in a production app but requires some improvements.

3. I believe that after releasing stable 3.0 or just before, I'll update the example repository since it is a bit abandoned in terms of the current availability of feature set.

**Comment by enricosecondulfo** [comment]
Thank you so much for your exhaustive answer
