### ISSUE TITLE
Implement cookie-parser middleware

### ISSUE THREAD

**Issue by mistyharsh** [marblejs/marble#83]
### Problem statement:
I intend to build **cookie parser** middleware similar to what Hapi or Express has. Additionally, provide helper functions to manage cookie lifecycle.

### Solution:
Originally, I intended to build cookie parser as part of [marble-mix](https://github.com/mistyharsh/marble-mix). But after some thought, I believe cookie-parsing should be part of official **marblejs**. I also doubt if monorepo is the right thing to do with cookies middleware as it doesn't really form the crux of marble. Additionally, this middleware will not be changing once stabilized. Seems no point in bumping version each time with Lerna.

**Implementation:**

1. Build on top of proven [cookie](https://www.npmjs.com/package/cookie) and [cookie-signature](https://www.npmjs.com/package/cookie-signature) or [cookies](https://www.npmjs.com/package/cookies).
2. Decorate request object with `state` which will basically be the `Record<string, string>`. Or it could be the ES Proxy object for some enhanced behavior.
3. Provide additional helpers to deal with setting cookies as part of the response. - The idea is not fully clear right now. But it will be similar to Hapi.js way of handling things.

### Questions:

1. What are your thought about this middleware?
2. If it should be part of an official marble ecosystem, should it be part of this monorepo or separate repo?
3. Will you accept PR for this middleware?
4. Also, does the concept of response middleware exists with marblejs?
5. If I am going to decorate incoming request object with `state`, how should I do it? Just add additional key? Same question as [stackoverflow question](https://stackoverflow.com/q/53406881/5723098).

**Comment by JozefFlakus** [comment]
Hi @mistyharsh, thanks for pointing this topic out!

Your doubts are correct, the `cookies` and any other form of state management doesn't fit well with the Marble.js philosophy - mainly because it **tries** to be functional but not in the pure FP form. The second thing is that `cookie` and `session` management is not recommended when we are talking about REST API's - in the ideal scenario the state should be handled via the client, not the server, but on the other side there are some cases in which cookies are handy to use, eg. authentication.

In general, it could be a Marble.js middleware, but I would like to not include it here. Due to mentioned functional attraction, marking it as an official middleware could result in some misunderstandings, eg.

> If it tries to be functional and dedicated for REST APIs, why does it allow for server state handling?

Reducing the possible list of features, especially for http server state management will indicate the new Marble users that it does not recommend some ways of doing it. The initial idea of Marble.js is just a request passing in a functional, reactive form so having the possible state in the middle of the pipeline is not what we want to deal and bother with.

**Regarding some implementation details:**
The `HttpRequest` interface allows for any sort of additional attributes that can be included inside the request. Simply, just add an additional key. Why this way? Just to deal with request object passing in more performant way. 😅 

If you would like to include missing types for added keys, just use "Module Augmentation" mechanism.

Big thanks for support! 💪 

P.S. What do you mean by "_response middleware_" ?

**Comment by mistyharsh** [comment]
Thank you @JozefFlakus. The most definite thing I can conclude here:

> Marble.js is aimed at REST API and alike. It is not a full-fledged framework and probably not meant for server-rendered or typical server-side API development.

As far as cookies are concerned, webapps having dedicated a **ui-server** and **api-server**, where client-side code directly connects to api-server with CORS; session cookie set by ui-server as authentication mechanism is common use-case. But, it should be pretty trivial to implement this as community middleware. And, completely agree with the reasoning why it should be out of core.

As far as the Response middleware is concerned, I meant a response interceptor to modify certain type of responses for various reasons. Such as when `Accept` header is `application/vnd.api+json`, so maybe there is a stream of outgoing message which can be use to adjust the response accordingly. The API endpoint should worry only about resource being worked on. The exact data sent over wire or its representation is orthogonal to the API endpoint. Or in other case, when `RouteEffect` sends 404 as a status code. It will be intercepted by common code that will send approapriate message depending upon the **Accept** header.

**Comment by JozefFlakus** [comment]
I don't see any concerns about implementing a `cookie-parser` middleware, so the doors are open for implementation. 😄 As you mentioned - Marble.js is not a full-fledged framework with hundreds of possible features on board, but rather a **library that tries to be a framework** but for closed audience of reactive and especially functional programming freaks. The next major versions of Marble will definitely move more into FP world. 

Regarding the "response middleware" - this is something that I planned to add at the very beginning, even before official 1.0 release. We've just started thinking about version 2.0 and for sure this kind of response middleware/transformer/(?) will land in the next major version. 💪

**Comment by JozefFlakus** [comment]
I see that [marble-mix](https://www.npmjs.com/package/marble-mix) introduced the `cookie-parser middleware`. There are no updates on this topic since the end of November, so I will close this issue. If there will be any other things to discuss we can reopen it again. 😉
